# Generated by Django 4.2.6 on 2023-11-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='admin',
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
