# Generated by Django 4.2.6 on 2023-11-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0002_remove_invoice_admin_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
