# Generated by Django 4.2.6 on 2023-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0004_alter_agenttransaction3_invice_n_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransaction3',
            name='receipt_empty',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name=' فاتورة'),
        ),
    ]
