# Generated by Django 4.2.6 on 2023-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0006_alter_agenttransaction3_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransaction3',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='agenttransaction3',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='agenttransaction3',
            name='balance_last',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balncagentafter',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balncagentlast',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='costperone_price',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
