# Generated by Django 4.2.6 on 2023-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
