# Generated by Django 4.2.6 on 2023-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0009_purchase_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
