# Generated by Django 4.2.6 on 2023-11-20 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0010_category_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_pro',
            old_name='name',
            new_name='nameC',
        ),
        migrations.AlterField(
            model_name='category_pro',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
