# Generated by Django 4.2.6 on 2023-11-21 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0011_rename_name_category_pro_namec_alter_category_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
        migrations.AlterField(
            model_name='category_pro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Productx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة للقطعة')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع للقطعة')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='الشركة المصنعة')),
                ('quantity_in_stock', models.IntegerField(verbose_name='الكمية في المخزن')),
                ('product_image', models.ImageField(upload_to='products/', verbose_name='صورة المنتج')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro1.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'منتجات',
            },
        ),
    ]
