# Generated by Django 4.2.6 on 2023-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0012_category_alter_category_pro_id_productx'),
    ]

    operations = [
        migrations.AddField(
            model_name='productx',
            name='description',
            field=models.TextField(null=True, verbose_name='الوصف'),
        ),
    ]
