# Generated by Django 4.2.6 on 2023-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0013_productx_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
