# Generated by Django 4.2.6 on 2023-11-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0014_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productx',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='productx',
            name='measurement_unit',
            field=models.CharField(max_length=50, null=True, verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='productx',
            name='packing_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قيمة التعبئة'),
        ),
    ]
