# Generated by Django 4.2.6 on 2023-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0016_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='totalAmountbeforediscount',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
    ]
